on: [push, workflow_dispatch]

# Environment variables available to all jobs and steps in this workflow
env:
  CLUSTER_NAME: aks-bjorn-erik
  CLUSTER_RESOURCE_GROUP: rg-idporten-aks-bjorn-erik

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    
    # Set the target Azure Kubernetes Service (AKS) cluster. 
    - uses: azure/aks-set-context@v1
      with:
        creds: '${{ secrets.AZURE_CREDENTIALS }}'
        cluster-name: ${{ env.CLUSTER_NAME }}
        resource-group: ${{ env.CLUSTER_RESOURCE_GROUP }}
      id: login
    
    # Create namespace if doesn't exist
    - run: |
        kubectl create namespace ${{ github.sha }} --dry-run -o json | kubectl apply -f -
        
    - run: |
        helm install ${{ github.sha }} chart-source/azure-vote/ --namespace ${{ github.sha }}    
