name: Create ondemand environment

on: 
  pull_request:
    types: [ labeled ]

env:
  CLUSTER_NAME: aks-bjorn-erik
  CLUSTER_RESOURCE_GROUP: rg-idporten-aks-bjorn-erik

jobs:
  build:
    if: ${{ github.event.label.name == 'ondemand' }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    
    # Set the target Azure Kubernetes Service (AKS) cluster. 
    - uses: azure/aks-set-context@v1
      with:
        creds: '${{ secrets.AZURE_CREDENTIALS }}'
        cluster-name: ${{ env.CLUSTER_NAME }}
        resource-group: ${{ env.CLUSTER_RESOURCE_GROUP }}
    
    # Create namespace if doesn't exist
    - run: |
        kubectl create namespace ${{ github.event.pull_request.head.ref }} --dry-run -o json | kubectl apply -f -
        
    - run: |
        helm install app-${{ github.event.pull_request.head.ref }}  chart-source/azure-vote/ --namespace ${{ github.event.pull_request.head.ref }} 
        
    - uses: actions/github-script@v3
      with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: ${{ github.event.pull_request.head.ref }}
            })
