on: [workflow_dispatch, pull_request]
# Environment variables available to all jobs and steps in this workflow
env:
  CLUSTER_NAME: aks-bjorn-erik
  CLUSTER_RESOURCE_GROUP: rg-idporten-aks-bjorn-erik

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    
    # Set the target Azure Kubernetes Service (AKS) cluster. 
    - uses: azure/aks-set-context@v1
      with:
        creds: '${{ secrets.AZURE_CREDENTIALS }}'
        cluster-name: ${{ env.CLUSTER_NAME }}
        resource-group: ${{ env.CLUSTER_RESOURCE_GROUP }}
    
    # Create namespace if doesn't exist
    - run: |
        kubectl create namespace ${GITHUB_REF##*/} --dry-run -o json | kubectl apply -f -
        
    - run: |
        helm install app-${GITHUB_REF##*/}  chart-source/azure-vote/ --namespace ${GITHUB_REF##*/}  
        
    - uses: actions/github-script@v3
      with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "${GITHUB_REF}"
            })
