on: workflow_dispatch

jobs:
  list-all-pulls:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
                const pulls = await github.pulls.list({
                  owner: context.repo.owner,
                   repo: context.repo.repo,  
                })
                console.log(pulls.data[0].url)
