on: workflow_dispatch

jobs:
  welcome:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
                const pulls = github.pulls.list({
                    ...context.issue,
                    creator,
                    state: 'all'
                })
                console.log(pulls)
